optional buildjava

diff --git a/buildjava b/buildjava
--- a/buildjava
+++ b/buildjava
@@ -1,10 +1,33 @@
 #!/bin/sh
 if [ $# -eq 0 ]
 then
-	echo "Usage: buildjava project or buildjava project <1>"
+	echo "Usage: $0 -p project [-r] [-d JMXPORT]"
 	exit 1
 fi
-PROJECT=$(echo "$1" | sed 's/\.git$//');
+while getopts  :p:rd: OPTION; do
+
+    case $OPTION in
+        p)
+            PROJECT=$(echo "$OPTARG" | sed 's/\.git$//');
+        ;;
+        r)
+            RESET="1";
+        ;;
+            
+        d)
+            JMXPORT=$OPTARG;
+            if [[ $JMXPORT -le 0 ]] ; then
+                echo "DEBUG port invalid."
+                exit;
+            fi
+        ;;
+        ?)
+            echo "illegal option $OPTION $OPTARG"
+            exit 1;;
+
+    esac;
+done
+
 PROJECTFIXED="${PROJECT}.git"
 
 ROOT_PATH=$(env|grep HOME|awk -F '='   '{print $2}')"/software/buildjava"
@@ -31,13 +54,12 @@ git pull -p
 git submodule init
 git submodule update
 
-if [[ $2 == "1" ]] ; then
+if [[ $RESET == "1" ]] ; then
         echo "清理项目"
         mvn clean
 fi
 if [[ -f "$ROOT_PATH/$PROJECTFIXED/project.properties" ]] ; then
     INSTALL=$(cat project.properties|awk -F "=" '{print $2}')
-    #INSTALL=$(cat  "$ROOT_PATH/$PROJECTFIXED/project.properties"| grep ^install= | cut -c 9-10)
 else
     INSTALL=0;
 fi
@@ -54,9 +76,12 @@ else
     echo "编译项目"
     mvn package
     cd target
-    /usr/bin/nohup /usr/bin/java -jar -Dspring.cloud.config.profile=prod  $PROJECT.jar  2>&1 &
-
-    #print \n end nohup
+    if [[ $JMXPORT -gt 0 ]] ;then
+        /usr/bin/nohup /usr/bin/java -Dcom.sun.management.jmxremote.port=$JMXPORT -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -jar -Dspring.cloud.config.profile=prod  $PROJECT.jar  2>&1 &
+         
+    else
+            /usr/bin/nohup /usr/bin/java -jar -Dspring.cloud.config.profile=prod  $PROJECT.jar  2>&1 &
+    fi
     str=$"\n"
     sstr=$(echo -e $str)
     echo $sstr
